package com.spring.soap.ws.address;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2020-12-26T14:56:21.017+01:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://soap.spring.com/ws/address", name = "AddressBook")
@XmlSeeAlso({net.java.dev.jaxb.array.ObjectFactory.class, com.spring.soap.ws.address.data.ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface AddressBook {

    @WebMethod
    @WebResult(name = "return", targetNamespace = "http://soap.spring.com/ws/address", partName = "return")
    public int addContactSeparated(
        @WebParam(partName = "firstName", name = "firstName")
        java.lang.String firstName,
        @WebParam(partName = "lastName", name = "lastName")
        java.lang.String lastName,
        @WebParam(partName = "email", name = "email")
        java.lang.String email,
        @WebParam(partName = "phones", name = "phones")
        net.java.dev.jaxb.array.StringArray phones,
        @WebParam(partName = "defaultPhoneIndex", name = "defaultPhoneIndex")
        int defaultPhoneIndex
    );

    @WebMethod
    @WebResult(name = "return", targetNamespace = "http://soap.spring.com/ws/address", partName = "return")
    public com.spring.soap.ws.address.data.Contact getContact(
        @WebParam(partName = "index", name = "index")
        int index
    );

    @WebMethod
    @WebResult(name = "return", targetNamespace = "http://soap.spring.com/ws/address", partName = "return")
    public com.spring.soap.ws.address.data.ContactArray getContacts();

    @WebMethod
    public void removeContact(
        @WebParam(partName = "index", name = "index")
        int index
    );

    @WebMethod
    @WebResult(name = "return", targetNamespace = "http://soap.spring.com/ws/address", partName = "return")
    public int addContact(
        @WebParam(partName = "contact", name = "contact")
        com.spring.soap.ws.address.data.Contact contact
    );
}
