package com.spring.soap.ws.hello;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.4.1
 * 2020-12-25T18:27:06.541+01:00
 * Generated source version: 3.4.1
 *
 */
@WebService(targetNamespace = "http://soap.spring.com/ws/hello", name = "HelloDocument")
@XmlSeeAlso({com.spring.soap.ws.hello.types.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface HelloDocument {

    @WebMethod
    @WebResult(name = "ResponseMiss", targetNamespace = "http://soap.spring.com/ws/hello/types", partName = "ResponseMiss")
    public java.lang.String sayHelloMiss(

        @WebParam(partName = "RequestMiss", name = "RequestMiss", targetNamespace = "http://soap.spring.com/ws/hello/types")
        com.spring.soap.ws.hello.types.RequestMissType requestMiss
    );
}
