
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.spring.soap.ws.style.doc.bare;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import com.spring.soap.ws.style.doc.bare.types.Person;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2020-12-26T04:55:32.403+01:00
 * Generated source version: 3.2.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "HelloDocBareService",
                      portName = "HelloDocBarePort",
                      targetNamespace = "http://soap.spring.com/ws/style/doc/bare",
                      wsdlLocation = "classpath:wsdl/HelloDocBare.wsdl",
                      endpointInterface = "com.spring.soap.ws.style.doc.bare.HelloDocBare")
                      
public class HelloDocBarePortImpl implements HelloDocBare {

    private static final Logger LOG = Logger.getLogger(HelloDocBarePortImpl.class.getName());

    
    public HelloDocBarePortImpl() {
    	System.out.println("Create HelloDocBareImpl object");
    }
        
    /* (non-Javadoc)
     * @see com.spring.soap.ws.style.doc.bare.HelloDocBare#sayHello(com.spring.soap.ws.style.doc.bare.Person person)*
     */
    public java.lang.String sayHello(Person person) { 
        LOG.info("Executing operation sayHello");
        System.out.println(person);
        try {
        	System.out.println("Invoked HelloDocBarePortImpl sayHello() method");
    		return "Hello world " + person.getFirstName() + " " + person.getLastName();
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
