package com.spring.soap.ws.style.rpc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2020-12-26T04:55:32.792+01:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://soap.spring.com/ws/style/rpc", name = "HelloRPC")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface HelloRPC {

    @WebMethod
    @WebResult(name = "return", targetNamespace = "http://soap.spring.com/ws/style/rpc", partName = "return")
    public java.lang.String sayHelloSeparated(
        @WebParam(partName = "firstName", name = "firstName")
        java.lang.String firstName,
        @WebParam(partName = "lastName", name = "lastName")
        java.lang.String lastName
    );

    @WebMethod
    @WebResult(name = "return", targetNamespace = "http://soap.spring.com/ws/style/rpc", partName = "return")
    public java.lang.String sayHello(
        @WebParam(partName = "person", name = "person")
        Person person
    );
}
