package com.spring.soap.ws.style.rpc;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2020-12-26T04:55:32.801+01:00
 * Generated source version: 3.2.1
 * 
 */
@WebServiceClient(name = "HelloRPCService", 
                  wsdlLocation = "classpath:wsdl/HelloRPC.wsdl",
                  targetNamespace = "http://soap.spring.com/ws/style/rpc") 
public class HelloRPCService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://soap.spring.com/ws/style/rpc", "HelloRPCService");
    public final static QName HelloRPCPort = new QName("http://soap.spring.com/ws/style/rpc", "HelloRPCPort");
    static {
        URL url = HelloRPCService.class.getResource("wsdl/HelloRPC.wsdl");
        if (url == null) {
            url = HelloRPCService.class.getClassLoader().getResource("wsdl/HelloRPC.wsdl");
        } 
        if (url == null) {
            java.util.logging.Logger.getLogger(HelloRPCService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "wsdl/HelloRPC.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public HelloRPCService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HelloRPCService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloRPCService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public HelloRPCService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public HelloRPCService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public HelloRPCService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns HelloRPC
     */
    @WebEndpoint(name = "HelloRPCPort")
    public HelloRPC getHelloRPCPort() {
        return super.getPort(HelloRPCPort, HelloRPC.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloRPC
     */
    @WebEndpoint(name = "HelloRPCPort")
    public HelloRPC getHelloRPCPort(WebServiceFeature... features) {
        return super.getPort(HelloRPCPort, HelloRPC.class, features);
    }

}
