
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.spring.soap.ws.style.doc.wrap;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2020-12-26T07:28:56.702+01:00
 * Generated source version: 3.2.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "HelloDocWrappedService",
                      portName = "HelloDocWrappedPort",
                      targetNamespace = "http://soap.spring.com/ws/style/doc/wrap",
                      wsdlLocation = "classpath:wsdl/HelloDocWrapped.wsdl",
                      endpointInterface = "com.spring.soap.ws.style.doc.wrap.HelloDocWrapped")
                      
public class HelloDocWrappedPortImpl implements HelloDocWrapped {

    private static final Logger LOG = Logger.getLogger(HelloDocWrappedPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.spring.soap.ws.style.doc.wrap.HelloDocWrapped#sayHello(java.lang.String firstName, java.lang.String lastName)*
     */
    public java.lang.String sayHello(java.lang.String firstName, java.lang.String lastName) { 
        LOG.info("Executing operation sayHello");
        System.out.println(firstName);
        System.out.println(lastName);
        try {
        	System.out.println("Invoked HelloDocWrappedImpl sayHello() method");
    		return "Hello world " + firstName + " " + lastName;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
