package com.spring.soap.ws.style.doc.wrap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2020-12-26T07:28:56.713+01:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://soap.spring.com/ws/style/doc/wrap", name = "HelloDocWrapped")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloDocWrapped {

    @WebMethod
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://soap.spring.com/ws/style/doc/wrap", className = "com.spring.soap.ws.style.doc.wrap.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://soap.spring.com/ws/style/doc/wrap", className = "com.spring.soap.ws.style.doc.wrap.SayHelloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String sayHello(
        @WebParam(name = "firstName", targetNamespace = "")
        java.lang.String firstName,
        @WebParam(name = "lastName", targetNamespace = "")
        java.lang.String lastName
    );
}
