package com.spring.soap.ws.address;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2020-12-26T02:11:43.962+01:00
 * Generated source version: 3.2.1
 * 
 */
@WebServiceClient(name = "AddressBookService", 
                  wsdlLocation = "wsdl/AddressBook.wsdl",
                  targetNamespace = "http://soap.spring.com/ws/address") 
public class AddressBookService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://soap.spring.com/ws/address", "AddressBookService");
    public final static QName AddressBookPort = new QName("http://soap.spring.com/ws/address", "AddressBookPort");
    static {
        URL url = AddressBookService.class.getResource("wsdl/AddressBook.wsdl");
        if (url == null) {
            url = AddressBookService.class.getClassLoader().getResource("wsdl/AddressBook.wsdl");
        } 
        if (url == null) {
            java.util.logging.Logger.getLogger(AddressBookService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "wsdl/AddressBook.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public AddressBookService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AddressBookService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AddressBookService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public AddressBookService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public AddressBookService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public AddressBookService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns AddressBook
     */
    @WebEndpoint(name = "AddressBookPort")
    public AddressBook getAddressBookPort() {
        return super.getPort(AddressBookPort, AddressBook.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AddressBook
     */
    @WebEndpoint(name = "AddressBookPort")
    public AddressBook getAddressBookPort(WebServiceFeature... features) {
        return super.getPort(AddressBookPort, AddressBook.class, features);
    }

}
